security:
  encryption_key: "kunci_fernet_base64_32_byte"  # Hasil dari Fernet.generate_key()

payloads:
  mysql:
    - "gAAAAAB..."  # Payload SQLi terenkripsi untuk MySQL
    - "gAAAAAB..."  # Contoh: ' OR 1=1 -- 
  postgresql:
    - "gAAAAAB..."  # Payload SQLi terenkripsi untuk PostgreSQL
  # DBMS lainnya...

network:
  proxies:
    http: "http://proxy:port"      # Proksi HTTP opsional
    https: "https://proxy:port"    # Proksi HTTPS opsional
  timeout: 10                      # Timeout koneksi dalam detik

endpoints:
  google: "https://www.googleapis.com/customsearch/v1"  # Endpoint Google CSE

credentials:
  api_key: "your_google_api_key"   # API Key Google Custom Search
  cse_id: "your_cse_id"           # ID Mesin Pencari Kustom

stealth:
  referers:
    - "https://www.google.com"
    - "https://www.bing.com"
    - "https://duckduckgo.com"
  time_based_threshold: 3.5        # Ambang deteksi berbasis waktu (detik)

performance:
  threads: 15                      # Jumlah thread maksimum

detection_patterns:
  - "error in your SQL syntax"     # Pola error database umum
  - "Warning: mysql"
  - "PostgreSQL.*ERROR"
  - "ORA-[0-9]{5}"
  - "Microsoft OLE DB Provider"
